### ISSUE TITLE
Uncaught You must pass your app key when you instantiate Pusher.

### ISSUE THREAD

**Issue by bobper** [qirolab/laravel-reverb-chat#1]
after install 
on chat page 
chat form  not loaded  and gave this error on console :  
Uncaught You must pass your app key when you instantiate Pusher.

**Comment by kukukk** [comment]
Hi,

Did you defined the `REVERB_*` and `VITE_REVERB_*` env variables in the `.env` file?

**Comment by hkp22** [comment]
In your .env file, you should specify the reverb configurations.

```
REVERB_APP_ID=my-app-id
REVERB_APP_KEY=my-app-key
REVERB_APP_SECRET=my-app-secret
REVERB_HOST="localhost"
REVERB_PORT=8080
REVERB_SCHEME=http

VITE_REVERB_APP_KEY="${REVERB_APP_KEY}"
VITE_REVERB_HOST="${REVERB_HOST}"
VITE_REVERB_PORT="${REVERB_PORT}"
VITE_REVERB_SCHEME="${REVERB_SCHEME}"
```
